  services:
    postgres:
      image: postgres:13
      container_name: agrotis_postgres
      environment:
        POSTGRES_DB: agrotis_db
        POSTGRES_USER: agrotis_user
        POSTGRES_PASSWORD: agrotis_password
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    app:
      build: .
      container_name: agrotis_app
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agrotis_db
        SPRING_DATASOURCE_USERNAME: agrotis_user
        SPRING_DATASOURCE_PASSWORD: agrotis_password
      ports:
        - "8080:8080"
      command: [ "java", "-jar", "/app-service/app.jar" ]

  volumes:
    postgres_data: